### ISSUE TITLE
Emoji ne s’affiche plus

### ISSUE THREAD

**Issue by ProBatou** [T-TutoRapide/notify-ssh-login#8]
Bonjour, merci pour le code il fonctionne parfaitement petit soucis au niveau des emojis il ne s’affiche pas. 

petit correctif a appliquer sur la ligne

```shell
"description": "**Détails**\n \\👤 Utilisateur: '\`$(whoami)\`' \n \\🖥️ Host: '\`$(hostname)\`' \n \\🕐 Connexion: '\`$DATE\`' \n\n **Adresse IP**\n \\📡 IP: '\`${IP}\`' \n \\🌎 Pays: '\`$PAYS\`' \n \\🏙️ Ville: '\`$VILLE\`' \n \\📠 ISP: '\`${ISP}\`'", 
```

```shell
"description": "**Détails**\n 👤 Utilisateur: '\`$(whoami)\`' \n 🖥 Host: '\`$(hostname)\`' \n 🕐 Connexion: '\`$DATE\`' \n\n **Adresse IP**\n 📡 IP: '\`${IP}\`' \n 🌎 Pays: '\`$PAYS\`' \n 🏙 Ville: '\`$VILLE\`' \n 📠 ISP: '\`${ISP}\`'",
```

**Comment by ghost** [comment]
Bonjour, 

Aucun soucie de mon coté tout fonctionne sans les modification  
![](https://media.tutorapide.xyz/nty3guii22fj.png)

**Comment by ProBatou** [comment]
D’accord si ca peux servir un jour au pire, on sait jamais
![Capture d’écran   2022-03-07 à 17 15 31](https://user-images.githubusercontent.com/27163397/157073563-5a9a0b11-ba80-4ebb-a563-9fca20abd23f.png)
